### ISSUE TITLE
can you add support for dub too & filler

### ISSUE THREAD

**Issue by Rawknee-69** [benjoquilario/animehi-stream#18]
You can add support for dub too by using prop hasdub to ensure the anime has dub to that makes the dub component visible and if doesn't have dub then it should be shown and use isFiller that is in Imetadata prop to make sure that if isfiller is returned true then the colour of the respected episode tab turns into other colour

**Comment by benjoquilario** [comment]
Thank you for suggestions will implement it soon 😁, wait for the update

**Comment by Rawknee-69** [comment]
> Thank you for suggestions will implement it soon 😁, wait for the update

bro can ask me for help on anything you want , don't feel shy for doing that....

**Comment by Rawknee-69** [comment]
> Thank you for suggestions will implement it soon 😁, wait for the update

And use cros proxy for fetching episodes and other assets it will be fast and secure too

**Comment by benjoquilario** [comment]
Yeah thank you, I would love to see your code😁

**Comment by Rawknee-69** [comment]
> Yeah thank you, I would love to see your code😁

 i can't share this publicly so you can dm me on insta on @rawknee.69 so yeah
