### ISSUE TITLE
Watch now button gives u error 404

### ISSUE THREAD

**Issue by skgupta507** [benjoquilario/animehi-stream#24]
Hey @benjoquilario the watch now button gives u error instead of playing the anime episodes
It says 404 something went wrong. 
But when u click on the particular episode the anime plays without any errors
Can u look into it.

**Comment by benjoquilario** [comment]
I forgot to update the new url href path, it should be /watch?id=anilistId&slug=slug&episode=episodeNumber

I will update it

**Comment by skgupta507** [comment]
One more thing can i disturb u for cause my hosted instance does not fetch the most recent anime. It gives error failed to load and when u change the providers it gives me the 404 error. 
So can u help me out with it and explain this part of the .env more clearly
U have mentioned some variables where to find but some iam confused. 
Pls clear my confusion and solution for the error

ANIME_API_URI=http://localhost:9898
NEXT_PUBLIC_ANIME_API_URL=http://localhost:9898
#create one in https://github.com/Gratenes/m3u8CloudflareWorkerProxy
NEXT_PUBLIC_PROXY_URI=https://proxy?url
# I'm using gojo.live api only using it for recents episodes
ANIME_API_URI_V2=http://localhost:9898

#create on ANIME_API v2 in https://github.com/ghoshRitesh12/aniwatch-api
NEXT_PUBLIC_ANIME_API_URL_V2=http://localhost:9898
#create v3 in https://github.com/IrfanKhan66/hianime-mapper
NEXT_PUBLIC_ANIME_API_URL_V3=http://localhost:9898

Pls explain the above part why there are same variables 2 to 3 times

**Comment by skgupta507** [comment]
https://animehi-streamx.vercel.app/

My hosted site in which iam getting the error
