### ISSUE TITLE
Help Required [Episodes not showing]

### ISSUE THREAD

**Issue by skgupta507** [benjoquilario/animehi-stream#27]
Hey @benjoquilario can u help me with the issue that on my hosted instance episodes are not showing for any anime.
my site: https://animehi-streamx.vercel.app/

**Comment by benjoquilario** [comment]
make sure to check you api results if it's returning

**Comment by skgupta507** [comment]
> make sure to check you api results if it's returning

can u explain the `.env` for me

ANIME_API_URI=http://localhost:9898      `this here is consumet api`
NEXT_PUBLIC_ANIME_API_URL=http://localhost:9898    `here also consumet api` correct.

ANIME_API_URI_V2=http://localhost:9898    `this here Ghosh-ritesh ------ Aniwatch-api`  Right.


NEXT_PUBLIC_ANIME_API_URL_V2=http://localhost:9898      `BUT WHAT ABOUT THIS PLACE WHICH API SHULD WE USE HERE`


NEXT_PUBLIC_ANIME_API_URL_V3=http://localhost:9898          `this one here Hianime mapper`

SO IF U CAN EXPLAIN IT TO ME. THEN I THINK I MIGHT BE ABLE TO FIX THAT EPISODE NOT SHOWING.

MY API IS RESPONDING AND GIVING THE RESULTS IN OTHER PROJECTS I USED IT IN.

YOUR HELP WILL BE GREATLY APPRIECIATED @benjoquilario

**Comment by benjoquilario** [comment]
ANIME_API_V2 I'm using gojo.live api  i'm only using it for recent-episodes

**Comment by benjoquilario** [comment]
ANIME_API_V2 I'm using gojo.live api  i'm only using it for recent-episodes
NEXT_PUBLIC_ANIME_API_URL_V2 this should be the aniwatch api

**Comment by skgupta507** [comment]
> ANIME_API_V2 I'm using gojo.live api i'm only using it for recent-episodes NEXT_PUBLIC_ANIME_API_URL_V2 this should be the aniwatch api

Oh! ok i used aniwatch-api for the both variables.
also the `.env` file states that we need to add aniwatch-api to ANIME_API_V2.  that is y i was confused.
also where to find the gojo.live api.
