### ISSUE TITLE
Anilist Redirect URl example pls

### ISSUE THREAD

**Issue by Gupta507** [benjoquilario/animehi-stream#31]
Hey @benjoquilario can u help me with the Anilist redirect uri what do i need to put in the developer console.
I tried ------  https://{your-domain}/api/auth/callback/AniListProvider  and  https://{your-domain}/callback
what needs to be changed to make LOgin work.

**Comment by benjoquilario** [comment]
used https://{your-domain}/api/auth/callback/anilist

**Comment by Gupta507** [comment]
> used https://{your-domain}/api/auth/callback/anilist

thanks for the assist, it worked
